#spring.application.name=BootRESTAPIHelloWorldProon7thJan

server.port=4042

#Data Source configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ntspbms516
spring.datasource.username=root
spring.datasource.password=manager

#Hibernate JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.datasource-platform=org.hibernate.dialect.MySQL8Dialect

